### ISSUE TITLE
Could it be that the tool doesn't work anymore today (20/11/2023) ?

### ISSUE THREAD

**Issue by nicovn** [ehealthplatformstandards/laboResultVisualization#33]
https://fhir-testserver.be/index.php/visualization_webapp

When validating a message that used to validate without problems ... I now get Error 0 ...

**Comment by bdc-ehealth** [comment]
Indeed you were correct. The tools is working again now: see https://github.com/ehealthplatformstandards/laboResultVisualizationAPI/issues/5
