### ISSUE TITLE
Validation service is not working anymore (21/11/2023)

### ISSUE THREAD

**Issue by nicovn** [ehealthplatformstandards/laboResultVisualization#34]
For every message we get ERROR 500

Error: 500
Unable to connect to terminology server. Use parameter '-tx n/a' to run without using terminology services to validate LOINC, SNOMED, ICD-X etc. Error = Error fetching the server's capability statement: timeout

**Comment by bdc-ehealth** [comment]
@nicovn ,

we know this is a problem. It started with the international FHIR terminilogy server being down, but there appears to be an additional problem.

**Comment by bdc-ehealth** [comment]
@nicovn ,

the problem is solved
