### ISSUE TITLE
Exception evaluating OGNL expression: "patient.resource.identifier" (template: "patient" - line 5, col 51)

### ISSUE THREAD

**Issue by bdc-ehealth** [ehealthplatformstandards/laboResultVisualization#39]
@ec-ehealth 

[82470091998_013G050038_l_2_MOLIS_4.json](https://github.com/ehealthplatformstandards/laboResultVisualization/files/14165807/82470091998_013G050038_l_2_MOLIS_4.json)

**Comment by bdc-ehealth** [comment]
@frederic-istace

Hi Frederic, we have corrected the file you sent: now it visualizes correctly. Please be careful when using the "urn:uuid:" identifiers. The prefix should always be correct.
[istace_2.json](https://github.com/ehealthplatformstandards/laboResultVisualization/files/14167881/istace_2.json)

**Comment by frederic-istace** [comment]
@bdc-ehealth 
Thank you very much! I see my error know and was able to fix it. (The error messages returned by the validator are not always self explaining...)
