### ISSUE TITLE
Validation error: The fullUrl must be an absolute URL

### ISSUE THREAD

**Issue by nicovn** [ehealthplatformstandards/laboResultVisualization#40]
When validating resources that validated without any issues a couple of weeks ago we now get errors like the one below:

The fullUrl must be an absolute URL (not 'Patient/8799223d-eb81-445a-aee0-f50ef2e9fd57')

Is this a new/real error ? or a bug in the validation tool ?

Thanks a lot !

Nico

**Comment by bdc-ehealth** [comment]
@nicovn ,

you can read the full history of this error here: https://github.com/hl7-be/lab/issues/278
