### ISSUE TITLE
The visualizer displays too many times the specimen details of a laboratory report

### ISSUE THREAD

**Issue by JoostVanAverbeke** [ehealthplatformstandards/laboResultVisualization#5]
I think that the visualizer creates a "SPECIMEN DETAILS" button for every Observation that reference a specimen.
The specimen references are often identical.

The visualizer should not create extra "SPECIMEN DETAILS" buttons, when the specimen reference is identical.

Attach an example of a bundle

This example contains three different specimens

**Comment by JoostVanAverbeke** [comment]
Find the example of the json file here
https://github.com/hl7-be/hl7-be-fhir-laboratory-report/blob/master/testing/MIPS/UZG/bundle_2112221539.json

**Comment by ec-ehealth** [comment]
I cannot reproduce this, I think it has been fixed
