### ISSUE TITLE
Line breaks are sent in JSON (formatted as /r/n) but are not taken into account in the visualiser

### ISSUE THREAD

**Issue by LotteAd** [ehealthplatformstandards/laboResultVisualization#7]
(issue copied from Github for FHIR Laboratory Report)
Example case: https://github.com/hl7-be/hl7-be-fhir-laboratory-report/tree/master/testing/Macsys/815333047
![image](https://user-images.githubusercontent.com/93375157/148203426-ebdb1e39-4f3c-47b7-82d8-f6fca4a4d516.png)
(there is a line break between behandeld and te - between positieve and serologie - between en and in - between ; and afzonderlijk)

**Comment by ec-ehealth** [comment]
Line breaks is now displayed. This has been fixed
