### ISSUE TITLE
Result with "greater" or "less than" is displayed wrongly, should be with < or > - signs

### ISSUE THREAD

**Issue by LotteAd** [ehealthplatformstandards/laboResultVisualization#9]
(issue copied from Github for FHIR Laboratory Report)
![image](https://user-images.githubusercontent.com/93375157/148203680-a4f64331-e946-4074-90df-4a650728f24e.png)
Example: https://github.com/hl7-be/hl7-be-fhir-laboratory-report/blob/master/testing/Macsys/815333049/81365677998_815333049_11.json

**Comment by ec-ehealth** [comment]
Greater and lesser signs are now displayed correctly. This has been fixed
